```{r fig-2-setup}
knitr::opts_chunk$set(
  fig.path = "./fig-2/"
)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dev = c("png", "pdf")
)

library(scico)
library(factoextra)
library(ggrepel)
library(ggbeeswarm)
library(janitor)
library(broom)
library(patchwork)
library(cmdstanr)
library(brms)
library(stringr)
library(tidyverse)

custom_theme <- theme_bw(
  base_size = 10
  ) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
  )
theme_set(custom_theme)

scale_fill_scico_mid <- function(..., mid = 0, alpha = NULL, begin = 0, end = 1, direction = 1, reverse = TRUE, palette = "broc") {
  force(mid)
  ggplot2::continuous_scale(
    aesthetics = "fill",
    scale_name = "gradient2",
    palette = scales::gradient_n_pal(
      colours = scico::scico(256, alpha, begin, end, direction, palette),
      values = NULL, space = "Lab"
    ),
    guide = "colourbar",
    rescaler = function(x, to = c(0, 1), from = range(x, na.rm = TRUE)) {
      scales::rescale_mid(x, to, from, mid)
    },
    ...
  )
}
```

```{r loading}
aa_grouping <- c("G", "A", "S", "T", "C", "P", "V", "I", "L", "M", "F", "Y", "W", "N", "Q", "D", "E", "K", "R", "H", "*")
lehner_grouping <- c("*", "D", "E", "R", "H", "K", "S", "T", "N", "Q", "C", "G", "P", "A", "V", "I", "L", "M", "F", "W", "Y")

#-------------------------------------------------------------------------------
# dealing with un-normalized data

uas_annotation <- tribble(
  ~compound, ~concentration, ~dose,
  "aMSH", "1e-06", "high",
  "aMSH", "5e-08", "medium",
  "aMSH", "2e-08", "low",
  "None", "0", "zero",
  "THIQ", "1e-07", "high",
  "THIQ", "9e-09", "medium",
  "THIQ", "3e-09", "low",
)

uas_unnorm <- read_tsv("../sumstats/MC4R-DMS8-Gq-unnormalized.tsv") %>%
  separate(
    contrast, 
    into = c('compound', 'concentration', 'norm'), 
    remove = FALSE, 
    sep = '_'
  ) %>% 
  inner_join(uas_annotation)

#-------------------------------------------------------------------------------

cre_annotation <- tribble(
  ~compound, ~concentration, ~dose,
  "aMSH", "2e-08", "high",
  "aMSH", "5e-09", "medium",
  "aMSH", "5e-10", "low",
  "Forsk", "2.5e-05", NA,
  "None", "0", "zero",
  "THIQ", "1.2e-08", "high",
  "THIQ", "4e-09", "medium",
  "THIQ", "4e-10", "low"
)

cre_unnorm <- read_tsv("../sumstats/MC4R-DMS5-Gs-unnormalized.tsv") %>%
  separate(
    contrast, 
    into = c('compound', 'concentration', 'norm'), 
    remove = FALSE, 
    sep = '_'
  ) %>% 
  inner_join(cre_annotation)

unnorm_combo <- bind_rows(
  gs = cre_unnorm,
  gq = uas_unnorm,
  .id = "pathway"
) %>% 
  mutate(aa = if_else(aa == 'X', '*', aa))

#-------------------------------------------------------------------------------

cre <- read_tsv('../sumstats/MC4R-DMS5-Gs.tsv')

cre_dose <- tribble(
  ~contrast, ~dose, ~compound, ~concentration,
  "None_0_minus_Forsk_2.5e-05", "zero", "None", NA,
  "aMSH_2e-08_minus_Forsk_2.5e-05", "high", "aMSH", "2e-08",
  "aMSH_5e-09_minus_Forsk_2.5e-05", "medium", "aMSH", "5e-09",
  "aMSH_5e-10_minus_Forsk_2.5e-05", "low", "aMSH", "5e-10",
  "THIQ_1.2e-08_minus_Forsk_2.5e-05", "high", "THIQ", "1.2e-08",
  "THIQ_4e-09_minus_Forsk_2.5e-05", "medium", "THIQ", "4e-09",
  "THIQ_4e-10_minus_Forsk_2.5e-05", "low", "THIQ", "4e-10"
) %>%
  mutate(dose = factor(dose, levels = c("zero", "low", "medium", "high")))

cre <- cre %>%
  inner_join(cre_dose) %>% 
  rename(
    log2FoldChange = log2ContrastEstimate,
    log2StdError = log2ContrastError
  ) %>% 
  mutate(
    aa = if_else(aa == 'X', '*', aa),
    aa = factor(aa, levels = lehner_grouping)
    )

#-------------------------------------------------------------------------------

uas <- uas_unnorm %>%
  group_by(compound, dose) %>%
  mutate(
    p.adj = p.adjust(p.value, method = "BH")
  ) %>%
  ungroup() %>% 
  select(-norm)

cre_uas <- bind_rows(
  CRE = cre,
  UAS = uas,
  .id = "reporter"
) %>%
  select(reporter, compound, dose, chunk, pos, aa, log2FoldChange, log2StdError, statistic, p.value, p.adj) %>%
  mutate(
    dose = factor(dose, levels = c("zero", "low", "medium", "high")),
    aa = if_else(aa == 'X', '*', aa),
    aa = factor(aa, levels = lehner_grouping)
  )
```

## Main Figures

### aMSH Heatmap Split

Let's split the protein up in two and use patchwork to smash it together

```{r cre-amsh-heatmap, fig.width=12, fig.height=3}
amsh_top <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH",
    pos <= 175
  ) %>%
  ggplot(aes(x = pos, y = aa, fill = statistic)) +
  geom_tile() +
  coord_equal() +
  scale_fill_scico(palette = "vik", limits = c(-10, 10), oob = scales::squish) +
  theme_void()

amsh_bottom <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH",
    pos > 175
  ) %>%
  ggplot(aes(x = pos, y = aa, fill = statistic)) +
  geom_tile() +
  coord_equal() +
  scale_fill_scico(palette = "vik", limits = c(-10, 10), oob = scales::squish) +
  theme_void()

amsh_top +
  amsh_bottom +
  plot_layout(ncol = 1) +
  theme(legend.position = "none")
```

### aMSH Heatmap Long

```{r cre-amsh-heatmap-long, fig.width=1.5, fig.height=9}
amsh_long <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH"
  ) %>%
  ggplot(aes(y = pos, x = aa, fill = statistic)) +
  geom_tile() +
  coord_fixed(ratio = 1/3) +
  scale_fill_scico(palette = "vik", limits = c(-10, 10), oob = scales::squish) +
  scale_y_reverse() +
  theme_void() +
  theme(legend.position = 'none')

amsh_long
```

### Example Heatmaps

```{r all-heats, fig.width=24, fig.height=2}
heatmap_examples <- unnorm_combo %>%
  filter(compound != 'Forsk') %>% 
  mutate(
    pathway = factor(pathway, levels = c('gs', 'gq')),
    aa = factor(aa, levels = lehner_grouping),
    dose = factor(dose, levels = c("zero", "low", "medium", "high")),
    compound = if_else(compound == 'None', 'aMSH', compound),
    compound = factor(compound, levels = c("aMSH", "THIQ", "None", "Forsk"))
  ) %>%
  ggplot(aes(x = pos, y = aa, fill = statistic)) +
  geom_tile() +
  facet_grid(cols = vars(pathway, compound), rows = vars(dose)) +
  coord_equal() +
  scale_fill_scico(palette = "vik", limits = c(-10, 10), oob = scales::squish) +
  theme_void() +
  theme(legend.position = 'none')

heatmap_examples
```

### ClinVar

```{r clinvar-dists, fig.width=9, fig.height=3}
clinvar <- read_tsv("../data/annotations/MC4R-clinvar_20240105.tsv") %>%
  mutate(
    pos = as.numeric(str_sub(mut, 2, -2)),
    aa = str_sub(mut, -1, -1)
  )

clinvar_dists <- cre %>%
  left_join(clinvar) %>%
  mutate(
    significance = case_when(
      is.na(consequence) & aa == "*" ~ "Nonsense",
      is.na(consequence) ~ "Missense",
      grepl("pathogenic", consequence, ignore.case = TRUE) ~ "Pathogenic",
      grepl("benign", consequence, ignore.case = TRUE) ~ "Benign",
      TRUE ~ "VUS"
    ),
    color = case_when(
      p.adj < 0.01 & statistic < 0 ~ "#001260",
      p.adj < 0.01 & statistic > 0 ~ "#590007",
      TRUE ~ "grey"
    )
  )

clinvar_dists <- bind_rows(
  clinvar_dists,
  clinvar_dists %>%
    filter(significance %in% c("Pathogenic", "Benign", "VUS")) %>%
    mutate(significance = if_else(aa == "*", "Nonsense", "Missense"))
) %>% mutate(significance = factor(significance,
    levels = c("Nonsense", "Missense", "Pathogenic", "VUS", "Benign")))

clinvar_plot <- clinvar_dists %>%
  filter(
    dose == "low",
    compound == "aMSH"
  ) %>%
  ggplot(aes(x = fct_rev(significance), y = statistic, color = color)) +
  geom_quasirandom() +
  geom_hline(yintercept = 0, lty = "dashed") +
  coord_flip() +
  theme(legend.position = "none") +
  scale_color_identity() +
  ylab("Z-Statistic") +
  xlab("")

clinvar_plot
```

### gnomAD

```{r gnomad, fig.width=6, fig.height=6}
aa_table <- read_tsv(
  "../data/annotations/aa-letters.tsv",
  col_names = c("full", "three", "one")
) %>%
  select(-full)

gnomad_missense <- read_tsv("../data/annotations/MC4R-gnomAD_missense_20240108.tsv")

gnomad <- gnomad_missense %>%
  filter(`VEP Annotation` == "missense_variant") %>%
  select(`Protein Consequence`, `Allele Frequency`) %>%
  mutate(
    mut = str_remove(`Protein Consequence`, "p."),
    wt_aa = str_sub(mut, 1, 3),
    three = str_sub(mut, -3, -1),
    pos = as.numeric(str_sub(mut, 4, -4))
  ) %>%
  left_join(aa_table) %>%
  rename("aa" = "one")

gnomad_plot <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH"
  ) %>%
  inner_join(gnomad) %>%
  mutate(
    color = case_when(
      p.adj < 0.01 & statistic < 0 ~ "#001260",
      p.adj < 0.01 & statistic > 0 ~ "#590007",
      TRUE ~ "grey"
    )
  ) %>%
  ggplot() +
  geom_point(
    aes(x = log2FoldChange, y = log10(`Allele Frequency`), color = color)
  ) +
  geom_vline(xintercept = 0, lty = "dashed") +
  xlab("Log2(Fold Change vs WT)") +
  ylab("Log10(Allele Frequency)") +
  scale_color_identity()

gnomad_plot
```

### Literature Mutants

```{r huang-mutants, fig.width=4, fig.height=4}
huang2017 <- read_tsv("../data/annotations/MC4R-Huang2017.tsv") %>%
  mutate(
    group = str_replace(group, "L", " L"),
    group = factor(group, levels = c("Mild LoF", "Partial LoF", "Full LoF")),
    aa = if_else(mut_aa == "X", "*", mut_aa)
  ) %>%
  select(-mut_aa)

lit_mut_plot <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH"
  ) %>%
  inner_join(huang2017) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = "dashed") +
  geom_boxplot(
    aes(x = group, y = log2FoldChange),
    outlier.shape = NA
  ) +
  geom_quasirandom(aes(x = group, y = log2FoldChange)) +
  # theme(axis.text.x = element_text(angle = 45)) +
  xlab("") +
  ylab("Log2(Fold Change vs WT)")

lit_mut_plot
```

### Delta EC50s from Literature

```{r amsh-experimental-pec50s, fig.width=6, fig.height=6}
zhang <- read_csv("../data/annotations/mc4r-zhang-2021.csv")

crystal_wt <- zhang %>%
  filter(wt == "WT") %>%
  select(
    compound,
    pec50_wt = pec50,
    pec50_err_wt = pec50_err,
    emax_wt = emax,
    emax_err_wt = emax_err
  )

crystal_diff <- crystal_wt %>%
  inner_join(zhang) %>%
  mutate(
    rel_pec50 = (pec50 - pec50_wt),
    rel_pec50_err = sqrt(pec50_err^2 + pec50_err_wt^2),
    rel_pec50_z = rel_pec50 / rel_pec50_err,
    rel_emax = (emax - emax_wt),
    rel_emax_err = sqrt(emax_err^2 + emax_err_wt^2),
    rel_emax_z = rel_emax / rel_emax_err
  ) %>%
  filter(aa != "WT") %>%
  select(compound, location, wt, pos, aa, contains("rel"))

delta_ec50_plot <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH"
  ) %>%
  inner_join(crystal_diff) %>%
  filter(location == "Active Site") %>%
  ggplot(aes(x = statistic, y = rel_pec50)) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_point() +
  labs(
    x = "DMS Z-Score\n(Gs, aMSH, low concentration)",
    y = "aMSH ΔpEC50 for MC4R\nvariants (Relative to WT)"
  )

delta_ec50_plot
```

### Variant Classification

```{r class-proportions, fig.width=9, fig.height=4.5}
variant_class <- cre_uas %>%
  group_by(reporter, compound, dose) %>%
  mutate(
    class = case_when(
      statistic < 0 & p.adj < 0.01 ~ "Loss of Function",
      statistic > 0 & p.adj < 0.01 ~ "Gain of Function",
      TRUE ~ "WT-Like"
    ),
    class = factor(class, levels = c("Gain of Function", "WT-Like", "Loss of Function"))
  ) %>%
  ungroup() %>%
  count(reporter, compound, dose, class)

var_class_plot <- variant_class %>%
  filter(compound != "THIQ") %>%
  mutate(compound = "aMSH") %>%
  ggplot(aes(x = dose, y = n, fill = class)) +
  geom_col(position = "fill", color = "black") +
  facet_wrap(facets = vars(reporter), scales = "free_x") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = rev(c("#001260", "grey", "#590007"))) +
  theme(
    panel.grid.major.x = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  labs(
    x = "aMSH Dose",
    y = "Fraction of Variants"
  )

var_class_plot
```

## Patchwork

```{r fig-2, fig.width=8.5, fig.height = 10}
layout <- "
ABB
A#C
ADE
AFG
"

amsh_long + 
  free(heatmap_examples) + 
  clinvar_plot + 
  gnomad_plot + 
  lit_mut_plot + 
  delta_ec50_plot + 
  free(var_class_plot) +
  plot_layout(design = layout)
```

## Extended Figures

### aMSH Heatmap (Log2FC)

```{r cre-amsh-zoom-log2fc, fig.width=12, fig.height=3}
amsh_top <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH",
    pos <= 175
  ) %>%
  ggplot(aes(x = pos, y = aa, fill = log2FoldChange)) +
  geom_tile() +
  coord_equal() +
  scale_fill_scico_mid(palette = "cork", limits = c(-3, 1), mid = 0, oob = scales::squish) +
  theme_void()

amsh_bottom <- cre %>%
  filter(
    dose == "low",
    compound == "aMSH",
    pos > 175
  ) %>%
  ggplot(aes(x = pos, y = aa, fill = log2FoldChange)) +
  geom_tile() +
  coord_equal() +
  scale_fill_scico_mid(palette = "cork", limits = c(-3, 1), mid = 0, oob = scales::squish) +
  theme_void()

amsh_top +
  amsh_bottom +
  plot_layout(ncol = 1) +
  theme(legend.position = "none")
```

### Show of Force (Z's)

```{r show-of-force, fig.width=12, fig.height=10}
unnorm_combo %>%
  mutate(
    aa = factor(aa, levels = lehner_grouping),
    dose = factor(dose, levels = c("zero", "low", "medium", "high")),
    compound = factor(compound, levels = c("aMSH", "THIQ", "None", "Forsk"))
  ) %>%
  ggplot(aes(x = pos, y = aa, fill = statistic)) +
  geom_tile() +
  facet_grid(rows = vars(pathway, compound, dose)) +
  coord_equal() +
  scale_fill_scico(palette = "vik", limits = c(-10, 10), oob = scales::squish) +
  theme_void()
```

### Show of Force (Log2FC)

```{r show-of-force-log2fc, fig.width=12, fig.height=10}
unnorm_combo %>%
  mutate(
    aa = factor(aa, levels = lehner_grouping),
    dose = factor(dose, levels = c("zero", "low", "medium", "high")),
    compound = factor(compound, levels = c("aMSH", "THIQ", "None", "Forsk"))
  ) %>%
  ggplot(aes(x = pos, y = aa, fill = log2FoldChange)) +
  geom_tile() +
  facet_grid(rows = vars(pathway, compound, dose)) +
  coord_equal() +
  scale_fill_scico(palette = "cork", limits = c(-2, 2), oob = scales::squish) +
  theme_void() +
  labs(fill = "log2fc")
```
