```{r fig-1-setup}
knitr::opts_chunk$set(
  fig.path = "./fig-1/"
)
```

## Main Figures

## Extended Figures

### Library Dosing

```{r gs-drc}
library_luci <- bind_rows(
  Gq = read_csv("../data/nfat-dosing.csv"),
  Gs = read_csv("../data/cre-dosing.csv"),
  .id = "reporter"
)

library_luci_dmso <- library_luci %>%
  filter(conc == 0) %>%
  group_by(reporter, plate) %>%
  summarise(
    dmso = mean(luc),
    .groups = "drop"
  )

library_luci_norm <- library_luci %>%
  filter(conc > 0) %>%
  inner_join(library_luci_dmso) %>%
  mutate(fold = luc / dmso)

#-------------------------------------------------------------------------------
# modeling stuff

priors <- prior(normal(1, 1), nlpar = "slope", lb = 0) +
  prior(normal(emax, 1), nlpar = "emax") +
  prior(normal(ec50, 1), nlpar = "ec50")

# conc goes in linear so we log10 it here
bf_ll3 <- brms::bf(
  fold ~ 1 + (emax - 1) / (1 + 10^(slope * (ec50 - log10(conc)))),
  ec50 ~ -1 + drug,
  emax + slope ~ 1,
  nl = TRUE
)

# use this to pass the values to the brms function
stanvars_gs <- stanvar(3, name = "emax") +
  stanvar(-9, name = "ec50")

gs_model <- brm(
  formula = bf_ll3,
  data = library_luci_norm %>% filter(reporter == 'Gs'),
  prior = priors,
  stanvars = stanvars_gs,
  chains = 4,
  silent = 2,
  refresh = 0
)

gs_curve_parms <- gs_model %>% 
  tidy(effects = 'fixed') %>% 
   mutate(
    term = str_remove(term, '_\\(Intercept\\)'),
    term = str_remove(term, 'drug')
  ) %>% 
  select(term, estimate) %>% 
  pivot_wider(names_from = term, values_from = estimate)

gs_model
```

Same thing for Gq

```{r gq-drc}
stanvars_gq <- stanvar(2.5, name = "emax") +
  stanvar(-7, name = "ec50")

gq_model <- update(
  gs_model,
  newdata = library_luci_norm %>% filter(reporter == 'Gq'),
  prior = priors,
  stanvars = stanvars_gq,
  chains = 4,
  silent = 2,
  refresh = 0
)

gq_curve_parms <- gq_model %>% 
  tidy(effects = 'fixed') %>% 
   mutate(
    term = str_remove(term, '_\\(Intercept\\)'),
    term = str_remove(term, 'drug')
  ) %>% 
  select(term, estimate) %>% 
  pivot_wider(names_from = term, values_from = estimate)

gq_model
```

Now let's plot the predictions together!

```{r library-dosing, fig.width=9, fig.height=6}
# partially parameterize an LL3
gs_drc_helper <- function(ec50, conc){
  1 + (gs_curve_parms$emax - 1) / (1 + 10^(gs_curve_parms$slope * (ec50 - log10(conc))))
}

gs_drc_plot <- library_luci_norm %>%
  filter(reporter == 'Gs') %>% 
  ggplot() +
  geom_hline(yintercept = 1, lty = "dashed") +
  geom_point(
    aes(x = conc, y = fold, color = drug)
  ) +
  geom_function(
    fun = ~ partial(gs_drc_helper, gs_curve_parms$ec50_aMSH)(.x),
    color = "#1F77B4"
  ) +
  geom_function(
    fun = ~ partial(gs_drc_helper, gs_curve_parms$ec50_THIQ)(.x),
    color = "#FF7F0E"
  ) +
  labs(
    title = 'Gs Luciferase Assay'
  )

gq_drc_helper <- function(ec50, conc){
  1 + (gq_curve_parms$emax - 1) / (1 + 10^(gq_curve_parms$slope * (ec50 - log10(conc))))
}

gq_drc_plot <- library_luci_norm %>%
  filter(reporter == 'Gq') %>% 
  ggplot() +
  geom_hline(yintercept = 1, lty = "dashed") +
  geom_point(
    aes(x = conc, y = fold, color = drug)
  ) +
  geom_function(
    fun = ~ partial(gq_drc_helper, gq_curve_parms$ec50_aMSH)(.x),
    color = "#1F77B4"
  ) +
  geom_function(
    fun = ~ partial(gq_drc_helper, gq_curve_parms$ec50_THIQ)(.x),
    color = "#FF7F0E"
  ) +
  labs(
    title = 'Gq Luciferase Assay'
  )

gs_drc_plot + gq_drc_plot +
    plot_layout(
        guides = 'collect',
        axes = 'collect'
    ) &
    scale_y_continuous(limits = c(0.9,5)) &
    scale_x_log10(
        breaks = 10^seq(-12, -5),
        limits = c(1e-12, 1e-5),
        labels = scales::trans_format("log10", scales::math_format(10^.x))
    ) &
    scale_color_manual(values = c("#1F77B4", "#FF7F0E")) &
    labs(
        x = "Concentration",
        y = "Fold change relative to DMSO"
    ) &
    theme(
        legend.position = "bottom",
        legend.title = element_blank()
    )
```

### Effect of Barcodes

```{r barcode-downsample, fig.width=9, fig.height=4.5}
pos61p_downsample_sumstats <- read_tsv("./fig-1/MC4R-Downsample-Power-pos61P-downsample.tsv") %>%
  filter(mut_aa == "P")
pos90x_downsample_sumstats <- read_tsv("./fig-1/MC4R-Downsample-Power-pos90X-downsample.tsv") %>%
  filter(mut_aa == "*")

bind_rows(
  pos90x_downsample_sumstats %>% mutate(mut = "D90Stop"),
  pos61p_downsample_sumstats %>% mutate(mut = "E61P")
) %>%
  ggplot() +
  geom_pointrange(aes(
    x = as.factor(depth), y = estimate,
    ymin = estimate - 2 * std.error,
    ymax = estimate + 2 * std.error
  ), position = position_dodge2(width = 0.5)) +
  facet_wrap(~mut, nrow = 1) +
  geom_hline(yintercept = 0, lty = "dashed") +
  xlab("Number of Barcodes Per Sample") +
  ylab("Log2FoldChange\n+/- 2 Standard Errors")
```

### Correlation to Computational Predictions

```{r predictors, fig.width=10, fig.height=9}
alpha_missense <- read_tsv("../data/annotations/mc4r-alphamissense.tsv") %>%
  clean_names() %>%
  mutate(
    aa = str_sub(mut, start = -1, end = -1),
    pos = str_extract(mut, "\\d+") %>% as.numeric()
  )

alpha_missense_plot <- alpha_missense %>%
  mutate(score = -score + 1) %>%
  inner_join(cre) %>%
  filter(
    compound == "aMSH",
    dose == "low"
  ) %>%
  ggplot(aes(x = statistic, y = score)) +
  geom_point(pch = 21, alpha = 0.3) +
  labs(
    x = "DMS Z Score",
    y = "AlphaMissense score\n(0 = pathogenic, 1 = benign)"
  )

#-------------------------------------------------------------------------------

popeve <- read_csv("../data/annotations/mc4r-popeve.csv") %>%
  mutate(
    wt = str_sub(mutant, start = 1, end = 1),
    pos = str_extract(mutant, "\\d+") %>% as.numeric(),
    aa = str_sub(mutant, start = -1, end = -1)
  )

popeve_plot <- popeve %>%
  inner_join(cre) %>%
  filter(
    compound == "aMSH",
    dose == "low"
  ) %>%
  ggplot(aes(x = statistic, y = popEVE)) +
  geom_point(pch = 21, alpha = 0.3) +
  labs(
    x = "DMS Z Score",
    y = "popEVE Score"
  )

#-------------------------------------------------------------------------------

class_a <- read_tsv("../data/annotations/mc4r-class-a.tsv") %>%
  clean_names() %>%
  rename(class_a = cons, wt = wt_aa_short)

class_a_fit <- cre %>%
  filter(
    compound == "aMSH",
    dose == "low"
  ) %>%
  group_by(compound, dose, contrast, pos) %>%
  summarise(
    estimate = mean(log2FoldChange),
    z = mean(statistic),
    .groups = "drop"
  ) %>%
  inner_join(class_a) %>%
  augment(lm(class_a ~ z, data = .), data = .)

conservation_plot <- class_a_fit %>%
  ggplot() +
  geom_point(
    aes(x = z, y = class_a),
    pch = 21
  ) +
  geom_text_repel(
    aes(x = z, y = class_a, label = pos),
    data = filter(class_a_fit, .std.resid < -2),
    min.segment.length = 0,
    max.time = 2,
    force = 0.5,
    color = "red"
  ) +
  geom_line(aes(x = z, y = .fitted), linewidth = 1) +
  labs(
    x = "Mutational Tolerance Score",
    y = "Class-A GPCR Conservation"
  )

#-------------------------------------------------------------------------------

alpha_missense_plot +
  popeve_plot +
  conservation_plot +
  plot_layout(ncol = 2)
```


Write out aMSH data for both pathways with various predictors

```{r}
bind_rows(
  CRE = cre %>% filter(compound == "aMSH"),
  UAS = uas %>% filter(compound == "aMSH"),
  .id = "reporter"
) %>%
  mutate(
    pathway = if_else(reporter == "CRE", "Gs", "Gq")
  ) %>%
  clean_names() %>%
  select(reporter, pathway, compound, dose, chunk, pos, aa, log2fc = log2fold_change, std_error = log2std_error, statistic, p_value, p_adj) %>%
  left_join(alpha_missense) %>%
  rename(
    mutant = mut,
    am_score = score
  ) %>%
  relocate(mutant, .before = "pos") %>%
  select(-uniprot) %>%
  left_join(popeve) %>%
  relocate(wt, .before = "pos") %>%
  write_tsv("./fig-1/amsh-popeve-alphamissense.tsv")
```
